name: "Generate Snake"

on:
  # Controla quando a ação será executada. Neste caso, a cada 6 horas.
  schedule:
    - cron: "0 */6 * * *"

  # Permite que a ação seja executada manualmente.
  workflow_dispatch:

jobs:
  build:
    # O tipo de runner onde o job será executado.
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório.
      - uses: actions/checkout@v2

      # Gera o snake.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: YuriTals
          # Gera os arquivos em um branch chamado "output".
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Mostra o status do repositório para depuração.
      - run: git status

      # Faz o push das mudanças.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Publica os arquivos no branch "output".
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
